# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='rating',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=10, null=True),
        ),
    ]
