# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onuser',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
