# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_onuser_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='carddistibutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carddistibutors', to='game.Onuser'),
        ),
    ]
