# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_offuser_onuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offuser',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onuser',
            name='user',
            field=models.IntegerField(),
        ),
    ]
