# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170605_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offuser',
            name='user',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onuser',
            name='user',
            field=models.TextField(),
        ),
    ]
