# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170606_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='onuser',
            name='ingame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='major_amount',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='major_player',
            field=models.TextField(default=0),
        ),
    ]
