# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170620_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_sc', models.IntegerField(default=2)),
                ('current_sc', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_sc',
        ),
        migrations.RemoveField(
            model_name='player',
            name='final_sc',
        ),
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sets',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
