# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170620_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='major_amount',
            new_name='call_amount',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='major_card',
            new_name='call_card',
        ),
        migrations.RemoveField(
            model_name='team',
            name='major_player',
        ),
        migrations.AddField(
            model_name='team',
            name='call_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Onuser'),
        ),
        migrations.AlterField(
            model_name='offuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Onuser'),
        ),
    ]
