# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20170620_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='cardon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='call_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='turn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Onuser'),
        ),
    ]
