# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20170621_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='turn',
        ),
        migrations.AddField(
            model_name='player',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
