# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170621_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
