# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
