# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_player_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
