# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20170622_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='call_amount',
            field=models.IntegerField(default=4),
        ),
    ]
