# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20170622_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='cardon',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
