# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20170624_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='cardon',
            field=models.IntegerField(null=True),
        ),
    ]
