# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20170624_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sets',
            name='cardon',
        ),
        migrations.AddField(
            model_name='team',
            name='cardon1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='cardon2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='cardon3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='cardon4',
            field=models.IntegerField(null=True),
        ),
    ]
