# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20170624_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardon', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='cardon1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cardon2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cardon3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cardon4',
        ),
        migrations.AddField(
            model_name='cardon',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team'),
        ),
    ]
