# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_card_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='call_card',
            field=models.IntegerField(null=True),
        ),
    ]
