# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20170626_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='carddistibutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Onuser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='call_card',
            field=models.IntegerField(default=3),
        ),
    ]
