# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20170627_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Onuser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='carddistibutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Onuser'),
        ),
    ]
