# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20170627_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='call_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Onuser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='carddistibutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
