# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20170627_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
