# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20170628_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='call_card',
            field=models.IntegerField(default=1),
        ),
    ]
