# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20170629_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Onuser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='call_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Onuser'),
        ),
    ]
